import type { Product, Category, Address } from "@/types";

export const flashDeals: Product[] = [
  {
    id: "p1",
    category: "OTC Medicines",
    slug: "paracetamol-500mg-tablets",
    name: "Paracetamol 500mg Tablets",
    genericGroup: "Analgesics & Antipyretics",
    manufacturer: "Beximco Pharmaceuticals Ltd.",
    brand: "Napa",
    image:
      "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=600&auto=format&fit=crop",
    rating: 4.8,
    reviewCount: 2341,
    price: 25,
    originalPrice: 60,
    discountPercent: 58,
    badge: "Best Seller",
    inStock: true,
    stockCount: 248,
    requiresPrescription: false,
    composition: "Paracetamol BP 500mg",
    dosage: "Adults & children over 12: 1–2 tablets every 4–6 hours. Max 8 tablets in 24 hours.",
    description:
      "Napa (Paracetamol) Tablet is used for the treatment of mild to moderate pain and fever. It helps relieve various types of pain including headache, muscle pain, backache, toothache and menstrual cramps.",
  },
  {
    id: "p2",
    category: "Supplements",
    slug: "vitamin-d3-b12-supplement",
    name: "Vitamin D3 + B12 Supplement",
    genericGroup: "Vitamins & Supplements",
    manufacturer: "Square Pharmaceuticals Ltd.",
    brand: "A-Cal D3",
    image:
      "https://images.unsplash.com/photo-1550572017-edd951b55104?q=80&w=600&auto=format&fit=crop",
    rating: 4.7,
    reviewCount: 1892,
    price: 350,
    originalPrice: 700,
    discountPercent: 50,
    badge: "Flash Deal",
    inStock: true,
    stockCount: 92,
    requiresPrescription: false,
    composition: "Cholecalciferol (Vitamin D3) 2000 IU + Methylcobalamin (Vitamin B12) 500mcg",
    dosage: "1 capsule daily after meals, or as directed by physician.",
    description:
      "A-Cal D3 Vitamin D3 + B12 Capsules are formulated to support bone health, nerve function, and overall immunity. Each capsule delivers an optimal dose of both vitamins for comprehensive daily support.",
  },
  {
    id: "p3",
    category: "Prescription Drugs",
    slug: "azithromycin-500mg",
    name: "Azithromycin 500mg",
    genericGroup: "Antibiotics",
    manufacturer: "Incepta Pharmaceuticals Ltd.",
    brand: "Azimax",
    image:
      "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?q=80&w=600&auto=format&fit=crop",
    rating: 4.5,
    reviewCount: 4120,
    price: 65,
    originalPrice: 140,
    discountPercent: 54,
    badge: "Top Rated",
    inStock: true,
    stockCount: 130,
    requiresPrescription: true,
    composition: "Azithromycin Dihydrate BP eq. to Azithromycin 500mg",
    dosage: "As prescribed by physician. Do not self-medicate with antibiotics.",
    description:
      "Azimax is a broad-spectrum antibiotic used to treat a wide variety of bacterial infections including respiratory tract, ear, and skin infections. A valid prescription is required.",
  },
  {
    id: "p4",
    category: "Supplements",
    slug: "omega-3-fish-oil-1000mg",
    name: "Omega-3 Fish Oil 1000mg",
    genericGroup: "Vitamins & Supplements",
    manufacturer: "Renata Limited",
    brand: "HealthAid",
    image:
      "https://images.unsplash.com/photo-1584362917165-526a968579e8?q=80&w=600&auto=format&fit=crop",
    rating: 4.6,
    reviewCount: 987,
    price: 580,
    originalPrice: 1150,
    discountPercent: 50,
    badge: "Flash Deal",
    inStock: true,
    stockCount: 60,
    requiresPrescription: false,
    composition: "Fish Oil (providing EPA 180mg + DHA 120mg) 1000mg",
    dosage: "1 softgel daily with meals, or as directed by physician.",
    description:
      "HealthAid Omega-3 Fish Oil supports heart, brain, and joint health with a concentrated dose of EPA and DHA fatty acids sourced from deep-sea fish.",
  },
];

export const popularProducts: Product[] = [
  {
    id: "p5",
    category: "Prescription Drugs",
    slug: "metformin-500mg",
    name: "Metformin 500mg",
    genericGroup: "Antidiabetics",
    manufacturer: "Opsonin Pharma Ltd.",
    brand: "Glucomet",
    image:
      "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?q=80&w=600&auto=format&fit=crop",
    rating: 4.3,
    reviewCount: 785,
    price: 45,
    originalPrice: 88,
    discountPercent: 49,
    inStock: true,
    stockCount: 300,
    requiresPrescription: true,
  },
  {
    id: "p6",
    category: "OTC Medicines",
    slug: "cetirizine-10mg",
    name: "Cetirizine 10mg",
    genericGroup: "Antihistamines",
    manufacturer: "Square Pharmaceuticals Ltd.",
    brand: "Alatrol",
    image:
      "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=600&auto=format&fit=crop",
    rating: 4.4,
    reviewCount: 1543,
    price: 35,
    originalPrice: 70,
    discountPercent: 50,
    inStock: true,
    stockCount: 400,
    requiresPrescription: false,
  },
  {
    id: "p7",
    category: "Supplements",
    slug: "whey-protein-isolate",
    name: "Whey Protein Isolate",
    genericGroup: "Supplements",
    manufacturer: "ACI Limited",
    brand: "MuscleMax",
    image:
      "https://images.unsplash.com/photo-1550572017-edd951b55104?q=80&w=600&auto=format&fit=crop",
    rating: 4.5,
    reviewCount: 3201,
    price: 1850,
    originalPrice: 3500,
    discountPercent: 47,
    inStock: true,
    stockCount: 40,
    requiresPrescription: false,
  },
  {
    id: "p8",
    category: "Supplements",
    slug: "multivitamin-minerals",
    name: "Multivitamin + Minerals",
    genericGroup: "Vitamins & Supplements",
    manufacturer: "Drug International Ltd.",
    brand: "Vitabion",
    image:
      "https://images.unsplash.com/photo-1584362917165-526a968579e8?q=80&w=600&auto=format&fit=crop",
    rating: 4.2,
    reviewCount: 2109,
    price: 540,
    originalPrice: 900,
    discountPercent: 40,
    inStock: false,
    requiresPrescription: false,
  },
];


const moreProducts: Product[] = [
  {
    id: "p9",
    category: "Medical Devices",
    slug: "digital-thermometer",
    name: "Digital Thermometer",
    genericGroup: "Thermometers",
    manufacturer: "HealthTech Bangladesh Ltd.",
    brand: "MediCare",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=600&auto=format&fit=crop",
    rating: 4.5,
    reviewCount: 1210,
    price: 350,
    originalPrice: 500,
    discountPercent: 30,
    inStock: true,
    stockCount: 120,
    requiresPrescription: false,
  },
  {
    id: "p10",
    category: "Medical Devices",
    slug: "blood-pressure-monitor",
    name: "Automatic Blood Pressure Monitor",
    genericGroup: "Monitoring Devices",
    manufacturer: "HealthTech Bangladesh Ltd.",
    brand: "CardioCheck",
    image: "https://images.unsplash.com/photo-1550572017-edd951b55104?q=80&w=600&auto=format&fit=crop",
    rating: 4.6,
    reviewCount: 860,
    price: 2450,
    originalPrice: 3500,
    discountPercent: 30,
    inStock: true,
    stockCount: 35,
    requiresPrescription: false,
  },
  {
    id: "p11",
    category: "Medical Devices",
    slug: "glucometer-kit",
    name: "Glucometer Kit with 25 Strips",
    genericGroup: "Diabetes Care",
    manufacturer: "Diabetec Care Ltd.",
    brand: "GlucoCheck",
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?q=80&w=600&auto=format&fit=crop",
    rating: 4.4,
    reviewCount: 1540,
    price: 1250,
    originalPrice: 1800,
    discountPercent: 31,
    inStock: true,
    stockCount: 58,
    requiresPrescription: false,
  },
  {
    id: "p12",
    category: "Personal Care",
    slug: "antiseptic-liquid-500ml",
    name: "Antiseptic Liquid 500ml",
    genericGroup: "Antiseptics",
    manufacturer: "ACI Limited",
    brand: "CleanGuard",
    image: "https://images.unsplash.com/photo-1584362917165-526a968579e8?q=80&w=600&auto=format&fit=crop",
    rating: 4.7,
    reviewCount: 3320,
    price: 180,
    originalPrice: 220,
    discountPercent: 18,
    inStock: true,
    stockCount: 210,
    requiresPrescription: false,
  },
  {
    id: "p13",
    category: "Personal Care",
    slug: "hand-sanitizer-250ml",
    name: "Hand Sanitizer 250ml",
    genericGroup: "Hygiene",
    manufacturer: "Square Toiletries Ltd.",
    brand: "PureHands",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=600&auto=format&fit=crop",
    rating: 4.3,
    reviewCount: 2210,
    price: 120,
    originalPrice: 180,
    discountPercent: 33,
    inStock: true,
    stockCount: 340,
    requiresPrescription: false,
  },
  {
    id: "p14",
    category: "Herbal & Unani",
    slug: "pure-honey-500g",
    name: "Pure Honey 500g",
    genericGroup: "Natural Products",
    manufacturer: "Natural Nest Foods",
    brand: "Natural Nest",
    image: "https://images.unsplash.com/photo-1550572017-edd951b55104?q=80&w=600&auto=format&fit=crop",
    rating: 4.6,
    reviewCount: 980,
    price: 650,
    originalPrice: 800,
    discountPercent: 19,
    inStock: true,
    stockCount: 75,
    requiresPrescription: false,
  },
  {
    id: "p15",
    category: "Herbal & Unani",
    slug: "black-seed-oil-250ml",
    name: "Black Seed Oil 250ml",
    genericGroup: "Herbal Oils",
    manufacturer: "Hamdard Laboratories",
    brand: "Habbatus",
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?q=80&w=600&auto=format&fit=crop",
    rating: 4.5,
    reviewCount: 1430,
    price: 420,
    originalPrice: 600,
    discountPercent: 30,
    inStock: true,
    stockCount: 90,
    requiresPrescription: false,
  },
  {
    id: "p16",
    category: "OTC Medicines",
    slug: "omeprazole-20mg",
    name: "Omeprazole 20mg Capsules",
    genericGroup: "Antacids & PPIs",
    manufacturer: "Eskayef Pharmaceuticals Ltd.",
    brand: "Losectil",
    image: "https://images.unsplash.com/photo-1584362917165-526a968579e8?q=80&w=600&auto=format&fit=crop",
    rating: 4.4,
    reviewCount: 2750,
    price: 90,
    originalPrice: 120,
    discountPercent: 25,
    inStock: false,
    
    requiresPrescription: false,
  },
];

export const allProducts: Product[] = [
  ...flashDeals,
  ...popularProducts,
  ...moreProducts,
];

export const categories: Category[] = [
  {
    id: "c1",
    name: "Prescription Drugs",
    icon: "💊",
    itemCount: "2,400+ medicines",
    colorClass: "bg-blue-50",
  },
  {
    id: "c2",
    name: "OTC Medicines",
    icon: "🩺",
    itemCount: "1,800+ products",
    colorClass: "bg-emerald-50",
  },
  {
    id: "c3",
    name: "Medical Devices",
    icon: "🩹",
    itemCount: "650+ devices",
    colorClass: "bg-amber-50",
  },
  {
    id: "c4",
    name: "Supplements",
    icon: "🌿",
    itemCount: "3,100+ supplements",
    colorClass: "bg-violet-50",
  },
];

export const navCategories = [
  "Prescription Drugs",
  "OTC Medicines",
  "Medical Devices",
  "Supplements",
  "Personal Care",
  "Herbal & Unani",
];

export const mockAddresses: Address[] = [
  {
    id: "addr1",
    label: "Home",
    recipientName: "Md. Rafiqul Islam",
    addressLine: "House 12, Road 5, Block A, Banani, Dhaka — 1213",
    phone: "+880 1711-234567",
    isDefault: true,
  },
  {
    id: "addr2",
    label: "Office",
    recipientName: "Md. Rafiqul Islam",
    addressLine: "Flat 4B, Block C, Gulshan-2, Dhaka — 1212",
    phone: "+880 1711-234567",
    isDefault: false,
  },
];

export const deliveryCities = [
  "Dhaka",
  "Chattogram",
  "Sylhet",
  "Rajshahi",
  "Khulna",
  "Mymensingh",
  "Cumilla",
  "Barishal",
];
